development:
  PORT:
  RACK_ENV:

  DATABASE_URL:
  DATABASE_NAME:
  DATABASE_HOST:
  DATABASE_PORT:
  DATABASE_POOL:
  DATABASE_USER:
  DATABASE_PASSWORD:

  REDIS_URL:
  REDIS_HOST:
  REDIS_PORT:

  DEVISE_SECRET_KEY:
  DEVISE_PEPPER:
  SECRET_KEY_BASE:

  S3_KEY:
  S3_SECRET:
  S3_TOKEN:
  S3_BUCKET:
  S3_REGION:

  SENDGRID_PASSWORD:
  SENDGRID_USERNAME:

  SUBSCRIPTION_COST_CITIZEN:
  SUBSCRIPTION_COST_DEPUTY:
  SUBSCRIPTION_COST_FAMILY3:
  SUBSCRIPTION_COST_FAMILY6:

  AUTHORIZE_NET_KEY:
  AUTHORIZE_NET_SECRET:
  AUTHORIZE_NET_ENV:

  FADV_API_USERNAME:
  FADV_API_PASSWORD:

  FADV_IT_ACCOUNT:
  FADV_IT_USER_ID:
  FADV_IT_PASSWORD:

  FADV_API_CANDIDATE_INVITATION_URL:
  FADV_API_CANDIDATE_INVITATION_WSDL:
  FADV_API_UPDATE_PASSWORD_URL:
  FADV_API_UPDATE_PASSWORD_WSDL:
  FADV_BACKGROUND_SEARCH_PACKAGE_ID:

  KNOWMADICS_USERID:
  KNOWMADICS_API_KEY:
  KNOWMADICS_ORG_NAME:

  KNOWMADICS_GET_USER_SUBSCRIPTION_URL:
  KNOWMADICS_SET_USER_SUBSCRIPTION_URL:
  KNOWMADICS_CREATE_USER_ACCOUNT_URL:
  KNOWMADICS_SIGN_ON_URL:
