# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7634e9793cca7226949ae9e473c63052e5567afd1fb14346da2cd7d9d9c6d4a6446fc9ce7c08a54048c86ce87b3fa36bc0cc03f8c91f009651a90dcbacdd3539

test:
  secret_key_base: 67da4556fcf8dbf580f66e4b3098ff1cabd717ee3931a92ff6bd3f52eac4309a9e32e052b1b3be5ebc503951772570fd086111e2503c3ecc0eed05b66b9a0049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
